name: climaticpark_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - jupyterlab
  - ipykernel
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - seaborn
  - folium
  - tensorflow=2.10
  - keras
  - h5py
  - geopandas
  - fiona
  - shapely
  - pip
  - pip:
      - click-plugins==1.1.1
      - cligj==0.7.2
      - suncalc==0.1.3
